---
title: "Lab 3 - ggplot"
author: "Gilbert Baracka"
date: "4/13/2022"
output:
  html_document:
    theme: cosmo
  pdf_document: default
---
# Premier League data for the 2018-2019 Season
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library("jsonlite")
library(lubridate)

```

```{r raw data, include=TRUE}
csv_file <- "https://pkgstore.datahub.io/sports-data/english-premier-league/season-1819_csv/data/916634f7ec37dd45c86159bc723eb340/season-1819_csv.csv"
data <-read.csv(csv_file)



```
```{r cleandata}
clean_data <- data %>% 
    select(Div:HTR) %>%
    filter(HomeTeam == "Man United" | AwayTeam == "Man United") %>%
    mutate(Date = dmy(Date))
    
print(clean_data)

```

## Plot Description

Manchester United goals per game at home throughout the season. 

## Plot

```{r myplot}
clean_data %>%
    filter(HomeTeam == 'Man United') %>%
    ggplot(aes(x = Date, y = FTHG)) + 
    geom_line(color = 'red') +
    scale_x_date(date_breaks = '1 week', date_labels = '%d %b') +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
    labs(x = 'Game Date', y='Goals',title='Manchester United Goals At Home')

```